Traceback (most recent call last):
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/christopherdavis/miniconda3/envs/scrape/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gp_top2 = {}

for gp, df_sub in df_odds.groupby("Group"):
    gp_top2[gp] = rng.choice(df_sub["Team"], size=2, replace=False, p=df_sub["Implied"])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m gp_top2 [38;5;241m=[39m {}
[1;32m      3[0m [38;5;28;01mfor[39;00m gp, df_sub [38;5;129;01min[39;00m df_odds[38;5;241m.[39mgroupby([38;5;124m"[39m[38;5;124mGroup[39m[38;5;124m"[39m):
[0;32m----> 4[0m     gp_top2[gp] [38;5;241m=[39m [43mrng[49m[38;5;241m.[39mchoice(df_sub[[38;5;124m"[39m[38;5;124mTeam[39m[38;5;124m"[39m], size[38;5;241m=[39m[38;5;241m2[39m, replace[38;5;241m=[39m[38;5;28;01mFalse[39;00m, p[38;5;241m=[39mdf_sub[[38;5;124m"[39m[38;5;124mImplied[39m[38;5;124m"[39m])

[0;31mNameError[0m: name 'rng' is not defined
NameError: name 'rng' is not defined

